### ISSUE TITLE
Select field type in schema is an array of strings when "Select Multiple" disabled

### ISSUE THREAD

**Issue by DevMude** [wp-graphql/wpgraphql-acf#104]
### Description

It should be just `String` not `[String]!`

### Steps to reproduce

Create a select field and query it in graphiQL

### WPGraphQL Version

1.17.0

### WPGraphQL For ACF Version

2.0.0-beta.5.1.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.2 Pro

### WordPress Version

6.3.1

### PHP Version

8.1.23

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by DevMude** [comment]
@jasonbahl Seems a little strange to me. I would consider single choice -> multiple choice a significant enough change in the field structure (i.e. data type stored) to justify a change to the schema. I use a lot of select fields and pretty much never use multiple choice, so it's a little cumbersome with type generation and array access.

All good though, is there a filter I can hook into to change the default schema type of select fields?

**Comment by jasonbahl** [comment]
@DevMude ya, my instinct when building the first version of the plugin was to have the schema follow that rule, but after learning from several folks that changing that setting to allow different inputs in the admin was causing breaking changes for the client application, we opted to change this so that the schema isn't changed based on this field setting. 

As mentioned, we will likely have a more explicit GraphQL setting that would allow you to set whether you want the schema to be list_of or not. 

In the mean time, you could use a filter like so: 

```
add_filter(
	'wpgraphql/acf/field_type_resolve_type',
	static function ( $resolve_type, $field_config, $acf_field ) {

		// here we're checking if the field type is 'select' and if it's not we bail and
		// return the default.
		// we could check anything on the field config here, though. Like a custom setting value,
		// or anything else to determine whether the field should return a different resolve_type or not
		if ( ! isset( $acf_field['type'] ) || 'select' !== $acf_field['type'] ) {
			return $resolve_type;
		}

		return 'String';
	},
	10,
	3
);
```

You would need to override the resolver as well, to make sure the resolver returns the same Type that the Schema says it will return (a string, instead of a list of strings) and you should be able to do that via the `wpgraphql/acf/field_type_resolver` filter.

**Comment by jasonbahl** [comment]
@DevMude fwiw, I added more context to a similar issue (re: allow multiple) about how the "allow multiple" field could be set and then changed in the future and how that change should not lead to a break in the schema and break client applications. 

Of course, you can filter the defaults for your needs, but we need to try and provide the best default for the widest use cases. 

https://github.com/wp-graphql/wpgraphql-acf/pull/116#issue-1980089593

**Comment by DevMude** [comment]
I arrived at a solution which reverts the "Select Multiple" toggle to a breaking change in the schema. Here it is:

```php
add_filter('wpgraphql/acf/field_type_resolve_type', 'resolve_select_field_type', 10, 3);
function resolve_select_field_type($resolve_type, $field_config, $acf_field) {
  if (!isset($acf_field['type']) || $acf_field['type'] !== 'select') {
    return $resolve_type;
  }

  if ($acf_field['multiple']) {
    return [
      'list_of' => 'String',
    ];
  } else {
    return 'String';
  }
}

add_filter('wpgraphql/acf/get_graphql_field_config', 'override_select_field_resolver', 10, 2);
function override_select_field_resolver($field_config, $instance) {
  $acf_field = $instance->get_acf_field();
  if (isset($acf_field['type']) && $acf_field['type'] === 'select') {
    $field_config['resolve'] = function ($node, array $args, AppContext $context, ResolveInfo $info) use ($acf_field, $instance) {
      $value = $instance->resolve_field($node, $args, $context, $info);
      if (empty($value) && !is_array($value)) {
        return null;
      }
      $value = is_array($value) ? $value : [$value];
      if (!$acf_field['multiple']) {
        $value = $value[0];
      }
      return $value;
    };
  }
  return $field_config;
}
```


@jasonbahl the following hooks didn't work:

- `wpgraphql/acf/field_type_resolver`
- `wpgraphql/acf/pre_resolve_acf_field`
- `wpgraphql/acf/field_value`

When trying to query a select field within a flexible layout or clone field. It only lets you filter on the value of the the top level clone field or flexible layout, not the fields nested inside those fields.

**Comment by jasonbahl** [comment]
@DevMude I opened a new issue to reproduce the hooks you said are not working: https://github.com/wp-graphql/wpgraphql-acf/issues/149

If you have any more context to share about that, please do in the new issue. Thanks! 🙏🏻

**Comment by marco910** [comment]
I've tested both code snippets of you @jasonbahl and @DevMude. When trying to query afterward, GraphQL returns an internal server error. Is that currently a bug?

(I'm using the select field nested in a repeater and/or flexible content field)

**Comment by jasonbahl** [comment]
@marco910 can you provide more info on what snippet(s) you tried? What were you expecting and what did you see? If you see "Internal Server Error" can you make sure "GraphQL DEBUG" is enabled and see if there's more info provided with the "Internal Server Error" and also check your server error logs.

**Comment by marco910** [comment]
@jasonbahl I'm trying to return select fields where the option "multiple" is disabled (where users only can select a single option) as string and not as array.

That's the filter I'm trying to use:
```
add_filter('wpgraphql/acf/field_type_resolve_type', function ($resolve_type, $field_config, $acf_field) {
    // If the field is not a select field, return the original resolved field type.
    if (!isset($acf_field['type']) || $acf_field['type'] !== 'select') {
        return $resolve_type;
    }

    // If the field is a select field, return the field type as a list of strings if the field is set to multiple.
    // Otherwise, return the field type as a single string.
    if ($acf_field['multiple']) {
        return [
            'list_of' => 'String',
        ];
    } else {
        return 'String';
    }
}, 10, 3);
```

After enabling "GraphQL Debug" I get this error:
```
"debugMessage": "Expected a value of type \"String\" but received: [\"horizontal\"]",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 10,
          "column": 11
        }
      ],
      "path": [
        "page",
        "pagebuilder",
        "sections",
        0,
        "modules",
        1,
        "direction"
      ]
    },
```

**Comment by marco910** [comment]
UPDATE: I managed this by adding another filter which looks like this:
```
add_filter('wpgraphql/acf/get_graphql_field_config', function ($field_config, $instance) {
    $acf_field = $instance->get_acf_field(); // Get the ACF field configuration.

    if (isset($acf_field['type']) && $acf_field['type'] === 'select') {
        $field_config['resolve'] = function ($node, array $args, $context, $info) use ($acf_field, $instance) {
            $value = $instance->resolve_field($node, $args, $context, $info); // Get the field value.
            // If the field value is empty and not an array, return null.
            if (empty($value) && !is_array($value)) {
                return null;
            }
            // If the field value is not an array, convert it to an array.
            $value = is_array($value) ? $value : [$value];
            // If the field is not set to multiple, return the first value.
            if (!$acf_field['multiple']) {
                $value = $value[0];
            }
            // Return the field value.
            return $value;
        };
    }

    return $field_config;
}, 10, 2);
```

This makes sure that the value is returned as a string or array of strings, depending on the field settings.
