### ISSUE TITLE
Clone Fields inherit the name of the cloned field

### ISSUE THREAD

**Issue by iamjonasmarlo** [wp-graphql/wpgraphql-acf#125]
### Description

I have a problem with the Clone Fields. These take over the name of the cloned field in the query.

Specifically, I have a field group with the name "Content" (content). Various fields are created here. Now I have a second field group with the name "Layout". Here there are two clones "MainContent" (maincontent) and "Sidebar" (sidebar). Both clone fields reference the "Content" (content) field group. The query now only displays "content", no longer "Sidebar".

![01](https://github.com/wp-graphql/wpgraphql-acf/assets/8004195/29e4bb6f-8b10-4ad1-b63b-786f1ea402d8)

![02](https://github.com/wp-graphql/wpgraphql-acf/assets/8004195/a3ad862d-e16d-4dbc-9ff8-c58d669d7b1f)

### Steps to reproduce

1) Create a Fieldgroup with some fields in it
2) Create a second Fieldgroup with two clones of the first one (the names are different)
3) Only one clone ist visible in the API

### WPGraphQL Version

1.19.0

### WPGraphQL For ACF Version

Version 2.0.0-beta.6.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

Pro | 6.2.3

### WordPress Version

6.4.1

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@iamjonasmarlo would you be able to provide an export of your ACF Field Groups so I can try to reproduce?

I believe you _might_ be structuring your ACF Field Groups in a way that _might_ not even work properly in a non-WPGraphQL environment. 

If you have a field "content" and clone it 2x on the same group, you will end up with 2 fields named "content" and when the data is saved in the database they will both end up having the same data. 

I could be mistaken though? Would love to see a Feld Group export if you have one. 

Thanks 🙏🏻

**Comment by iamjonasmarlo** [comment]
Hey @jasonbahl,
thanks for your fast reply - again! :)

I clone the "content" field twice, but I name each clone differently ("sidebar" and "content"). In the "old" plugin, two different groups were displayed in the API.

You will find a sample export in the appendix.

Thank you very much!
[acf-export-2023-11-17.json](https://github.com/wp-graphql/wpgraphql-acf/files/13395421/acf-export-2023-11-17.json)

**Comment by jasonbahl** [comment]
@iamjonasmarlo Thanks again for reporting this. 

Using your export, I was able to reproduce this and confirm that cloning a field group 2x on the same field group isn't properly respecting the `prefix_field_names` option. 

Hope to have a fix soon 🙏🏻

**Comment by jasonbahl** [comment]
So, the current behavior of WPGraphQL for ACF when an entire field group is cloned, is to apply the `${ClonedFieldGroup}_Fields` Interface to the Field Group that the field was cloned onto. 

I think this was perhaps an API design mistake. 

Instead of cloning the Interface onto the field group, I believe there needs to be a field that returns a Type that implements the interface. 

For example, given the JSON field group export provided in the issue, the (pseudo) Schema that is generated is: 

```graphql
type CustomContent implements SectionSections_Fields, ... {
  sections: [ SectionsSections_Layout]
}
```

What _should_ be generated, I believe, is something like: 

```graphql

type CustomContentContent implements SectionSections_Fields { 
  sections: [ SectionsSections_Layout]
}

type CustomContentSidebar implements SectionSections_Fields {
  sections: [ SectionsSections_Layout]
}
type CustomContent , ... {
  content: CustomContentContent
   sidebar: CustomContentSidebar
}
```

Then, one would be able to query like so: 

```graphql
{
  page(id:"/kitchen-sink/" idType:URI) {
    ...on WithAcfCustomContent {
      customContent {
        content {
          sections {
            __typename
            ...SectionLayouts
          }
        }
        sidebar {
          sections {
            __typename
            ...SectionLayouts
          }
        }
      }
    }
  }
}
```

This will be a breaking change to the Schema for anyone who has cloned one field group and successfully used it. 

For folks that have cloned the same field group 2x, this will be a bugfix, as they've not been able to query both cloned field groups at all.

**Comment by jasonbahl** [comment]
@iamjonasmarlo I've opened up a PR that I believe should resolve this. 

Would love to get feedback and see if it solves your situation or if there might be more work to be done. 🙏🏻

**Comment by jasonbahl** [comment]
@iamjonasmarlo actually, there might be a bit more work to be done. In a clean environment with _just_ the field group export above, it works. 

But when I tried on another install with more field groups, it's causing some errors. 

Need to investigate more 👀

**Comment by jasonbahl** [comment]
@iamjonasmarlo I pushed up some more changes to #136. I believe it's getting close, if you'd be willing to check it out. 

Attached is the .zip of the plugin at the state of the PR: [wpgraphql-acf.zip](https://github.com/wp-graphql/wpgraphql-acf/files/13654060/wpgraphql-acf.zip)

**Comment by jasonbahl** [comment]
I pushed up some more changes to account for fields within flex field layouts cloning field groups onto the flex field layout. 

Attached is the plugin with those changes: [wpgraphql-acf.zip](https://github.com/wp-graphql/wpgraphql-acf/files/13665169/wpgraphql-acf.zip)

**Comment by DevMude** [comment]
@jasonbahl I wish I had seen this issue 6 hours earlier, just spent all day trying to debug this haha. That latest plugin zip works great so far! Thank you!

Just fyi it causes a memory allocation error if you have a cyclic dependency of clone fields. E.g. clone field 1 that points to clone field 2 that points back to clone field 1. Not sure if you want to code for that edge case, but it was a mistake I made when setting up some fields (was meant to clone a group field not another clone field). Had to trash my field groups one at a time to see what was going on.

Btw my use case is using the ACF Extended plugin's "Layout Settings" clone field. And the layoutSettings graphql type was not resolving correctly (was always just returning a String), but now it is, thank you! Actual god send haha

**Comment by jasonbahl** [comment]
@DevMude ya, I definitely need to guard against cyclical clones! Good callout. I think I've found another issue with clones within layouts too. 

So definitely some more work to be done but getting close! 🙏
