### ISSUE TITLE
WPGraphQL Gutenberg ACF Taxonomy Field Return

### ISSUE THREAD

**Issue by jsimondshiebing** [wp-graphql/wpgraphql-acf#133]
### Description

Using the most recent version of this plugin the Taxonomy field type returns an array of all taxonomy term objects regardless of the values you set for the field. In the ACF the Taxonomy field has the option to select a specific Taxonomy to pull terms from (either a built in like Post Categories or a custom Taxonomy). You can also specify the return type to be either the Term Object or the Term ID. However regardless of what is selected here the query in GraphQL always resolves to an array of all of the Term Objects regardless of Taxonomy.

### Steps to reproduce

1. Create or edit an ACF Field Group.
2. Create or edit a field of type Taxonomy
3. Set the field's Taxonomy option to a list that contains valid Terms.
4. Connect the ACF Field Group to a Gutenberg Block.
5. Add the ACF Block to a page/post and set the field's value.
6. Query the page's editorBlocks for the Taxonomy field.
7. Should return either the Term Object or the Term ID of the value set on the block, however currently returns all terms.

### PHP or JSON export of the ACF Field Group(s)

```
[
    {
        "key": "group_62bb6efc4104c",
        "title": "Work Section",
        "fields": [
            {
                "key": "field_62bb6f210bc95",
                "label": "Heading",
                "name": "heading",
                "aria-label": "",
                "type": "text",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "show_in_graphql": 1,
                "default_value": "",
                "placeholder": "",
                "prepend": "",
                "append": "",
                "maxlength": ""
            },
            {
                "key": "field_62e1a46d2808f",
                "label": "Text",
                "name": "text",
                "aria-label": "",
                "type": "wysiwyg",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "show_in_graphql": 1,
                "default_value": "",
                "tabs": "all",
                "toolbar": "full",
                "media_upload": 1,
                "delay": 0
            },
            {
                "key": "field_62e1a39172382",
                "label": "Layout",
                "name": "layout",
                "aria-label": "",
                "type": "select",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "show_in_graphql": 1,
                "choices": {
                    "full": "Full Width",
                    "large": "Large Cards",
                    "medium": "Medium Cards",
                    "small": "Small Cards"
                },
                "default_value": "full",
                "allow_null": 0,
                "multiple": 0,
                "ui": 0,
                "return_format": "value",
                "ajax": 0,
                "placeholder": ""
            },
            {
                "key": "field_62e2c80dd16d7",
                "label": "Category",
                "name": "category",
                "aria-label": "",
                "type": "taxonomy",
                "instructions": "",
                "required": 1,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "taxonomy": "work-categories",
                "add_term": 0,
                "save_terms": 0,
                "load_terms": 0,
                "return_format": "object",
                "field_type": "select",
                "allow_null": 1,
                "bidirectional": 0,
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "category",
                "multiple": 0,
                "bidirectional_target": []
            },
            {
                "key": "field_62bb6f390bc96",
                "label": "Total Items",
                "name": "total_items",
                "aria-label": "",
                "type": "select",
                "instructions": "Total number of most recent Work items to show.",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "show_in_graphql": 1,
                "choices": {
                    "1": "1",
                    "2": "2",
                    "3": "3",
                    "4": "4",
                    "5": "5"
                },
                "default_value": 5,
                "allow_null": 1,
                "multiple": 0,
                "ui": 0,
                "return_format": "value",
                "ajax": 0,
                "placeholder": ""
            },
            {
                "key": "field_62bb6fb9632e4",
                "label": "Button",
                "name": "button",
                "aria-label": "",
                "type": "link",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "show_in_graphql": 1,
                "return_format": "array"
            }
        ],
        "location": [
            [
                {
                    "param": "block",
                    "operator": "==",
                    "value": "acf\/work-section"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": "",
        "active": true,
        "description": "",
        "show_in_rest": 0,
        "show_in_graphql": 1,
        "graphql_field_name": "workSection",
        "map_graphql_types_from_location_rules": 1,
        "graphql_types": [
            "AcfWorkSection"
        ]
    }
]
```

### WPGraphQL Version

1.19.0

### WPGraphQL For ACF Version

2.0.0-beta.6.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.4, Pro

### WordPress Version

6.3.2

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@jsimondshiebing I'm having trouble reproducing this. 

I see the "taxonomy" field you're using is filtered to the "work-categories" taxonomy. 

Is that Taxonomy set to show in GraphQL by chance?

Can you maybe screenshot the block as you see it in the Block editor for the post, then screenshot the GraphiQL IDE as you see it with the query and results?

## Reproductions

In my attempts to reproduce I've created an ACF Field Group that has a "Taxonomy" field. 

### No terms selected
When the field is set to no value:

![CleanShot 2023-12-28 at 19 33 16](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/13facd15-df69-4f50-8e9c-7a2c263861c9)

I can query and get no value, as expected: 

![CleanShot 2023-12-28 at 19 33 26](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/7d230f7e-295d-437b-8d5e-1141453339a9)

### One Term Selected

If I select 1 term:

![CleanShot 2023-12-28 at 19 36 13](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/72c3971f-0876-494c-8546-5ddd13b51ab7)

I see that one term returned for the field, as expected:

![CleanShot 2023-12-28 at 19 35 43](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/cde2c88f-5804-4402-8bd2-d897358f35bc)

### Multiple Terms Selected

If I select Multiple Terms:

![CleanShot 2023-12-28 at 19 37 15](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/d140cdfa-f605-41c8-a0bf-f3a4110c91d0)

I see the selected terms returned, as expected: 

![CleanShot 2023-12-28 at 19 37 37](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/ab263821-bbe2-46a2-a52c-9183eb468776)

-----

In any attempt to reproduce, I've not been able to get "all" taxonomy terms to be returned. 

I don't doubt there's a bug, as there easily could be, but I might not have all the information needed to reproduce 🤔 

If you could share a bit more about the data you have stored, how the UI looks, how the `<--code editor-->` for the blocks looks, and what the query/results looks like, that would be super helpful. 

----

I was able to identify a different bug re: the Taxonomy field type, however. 

If you set the field to "multi-select" and save multiple values, then change it back to single select, but don't update the saved values (leave multiple values saved as an array), then there is an error returned in the query: 

![CleanShot 2023-12-28 at 19 46 21](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/fb5d1a49-1575-46e4-9c9c-454479088038)

I have a PR to fix that error. Perhaps my PR might fix the issue you're having as well? I'd love to still reproduce it though, if possible.

**Comment by jasonbahl** [comment]
@jsimondshiebing I opened this PR to fix the bug I described. Curious if it also fixes your bug? https://github.com/wp-graphql/wpgraphql-acf/pull/148

**Comment by jsimondshiebing** [comment]
@jasonbahl thanks for the reply! taking a look back into this now and i can confirm the custom taxonomy is set to show_in_graphql and was working when using the wpgraphql/wpgraphql-gutenberg/wpgraphql-gutenberg-acf plugin setup. here is the taxonomy registration function found in our custom plugin
```php
function demo_custom_post_types() {
    register_post_type( 'work', array(
        'labels' => array(
            'name'                  => __( 'Work', 'Post type general name' ),
            'singular_name'         => __( 'Work', 'Post type singular name' ),
            'add_new'               => __( 'Add New' ),
            'add_new_item'          => __( 'Add New Work' ),
            'edit_item'             => __( 'Edit Work' ),
            'new_item'              => __( 'New Work' ),
            'all_items'             => __( 'All Work' ),
            'view_item'             => __( 'View Work' ),
            'search_items'          => __( 'Search Work' ),
            'not_found'             => __( 'No Work found' ),
            'not_found_in_trash'    => __( 'No Work found in the trash' ),
            'menu_name'             => __( 'Work' )
        ),
        'description'  => 'Work pages and shared content',
        'public'       => true,
        'supports'     => array(
            'title',
            'thumbnail',
            'page-attributes',
            'custom-fields',
            'excerpt',
            'editor',
            'author',
            'revisions'
        ),
        'rewrite'      => array(
            'slug'          => 'work',
            'with_front'    => false
        ),
        'hierarchical'  => true,
        'show_ui'       => true,
        'show_in_graphql'   => true,
        'graphql_single_name'   => 'work',
        'graphql_plural_name'   => 'allWork',
        'show_in_rest'  => true
    ));
    register_taxonomy_for_object_type( 'work-categories', 'work' );
}
add_action( 'init', 'demo_custom_post_types' );
```
here is a screenshot of the block as it appears in the editor on the page we are adding it to:

![image](https://github.com/wp-graphql/wpgraphql-acf/assets/45610279/2fa68a0d-2380-489e-8f93-b198675d337f)

and here is the response i'm getting from the graphql query:

![image](https://github.com/wp-graphql/wpgraphql-acf/assets/45610279/fd3a7089-c150-435d-a0d7-fd90d8425a52)

i'll give that pr a look and see if it resolves the issue

**Comment by jasonbahl** [comment]
@jsimondshiebing thanks!

FYI, I'll be out until Jan 4. So likely won't be able to follow up again until then. 

Appreciate the added details! Hoping we can get this figured out!

**Comment by jasonbahl** [comment]
@jsimondshiebing can you also toggle Gutenberg to the code editor view and screenshot the raw data that is saved for the field? Like what ids are saved?

**Comment by jsimondshiebing** [comment]
@jasonbahl just tested the plugin at the the pr linked and i'm still seeing this behavior, wonder if it's due to the fact that it's a custom taxonomy registered to a custom post type that's throwing it off? here's the raw data saved to the page:

![image](https://github.com/wp-graphql/wpgraphql-acf/assets/45610279/d0f4b790-1d8f-4788-ba76-826608f49e53)

looks like it's getting the category id of 115 which i can confirm is the right id for the default work category taxonomy

**Comment by jasonbahl** [comment]
@jsimondshiebing you shared the code to register the post type, but not the taxonomy. You did share this line: `register_taxonomy_for_object_type( 'work-categories', 'work' );` but I don't see the `register_taxonomy()` call. 

Can you share that as well so I can continue trying to reproduce?

**Comment by jasonbahl** [comment]
@jsimondshiebing I went ahead and added the following to register the taxonomy: 

```php
register_taxonomy( 'work-categories', 'work', [
	'show_in_graphql' => true,
	'graphql_single_name' => 'WorkCategory',
	'graphql_plural_name' => 'WorkCategories',
	'public' => true,
	'label' => 'Work Categories'
] );
```

And this code to register the ACF Block:

```php
add_action('acf/init', 'my_acf_blocks_init');
function my_acf_blocks_init() {

	// Check function exists.
	if( function_exists('acf_register_block_type') ) {

		// Register a testimonial block.
		acf_register_block_type(array(
			'name'              => 'work-section',
			'title'             => __('Work Section'),
			'description'       => __('DELETE ME'),
		));
	}
}
```

With that in place, I was able to add a post with the block like so:

![CleanShot 2024-01-05 at 16 13 52](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/96bc0fbd-b5e4-4405-adfa-3dca6925b6ef)

Which looks like the following in the code editor: 


![CleanShot 2024-01-05 at 16 16 48](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/d094c3bd-3d95-4593-b15d-636e1d8365e0)

```php
<!-- wp:acf/work-section {"name":"acf/work-section","data":{"field_62bb6f210bc95":"Work Heading...","field_62e1a46d2808f":"Work Text","field_62e1a39172382":"large","field_62e2c80dd16d7":"84","field_62bb6f390bc96":"5","field_62bb6fb9632e4":{"title":"test acf block…","url":"http://acf2.local/blog/2024/01/05/test-acf-block/","target":""}},"align":"","mode":"edit"} /-->
```

Then I'm able to query and I get the 1 selected category in the GraphQL response, as I would expect: 

![CleanShot 2024-01-05 at 16 20 59](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/42908bae-7298-4803-bee4-4e7b61e705d9)

```graphql
query {
  post(id:7104 idType:DATABASE_ID) {
    id
    title
    ...Blocks
  }
}

fragment Blocks on NodeWithEditorBlocks {
  editorBlocks {
    __typename
    ...WorkSectionFragment
  }
}

fragment WorkSectionFragment on AcfWorkSection {
  workSection {
    button {
      target
      title
      url
    }
    heading
    layout
    text
    category {
      nodes {
        name
      }
    }
  }
}
```

----

I'm curious if you can reproduce this in a clean WordPress install with only WPGraphQL and WPGraphQL for ACF v2.0.0 active?

I wonder if there's any other plugins or custom code that is maybe filtering underlying `WP_Query` / `WP_Term_Query` calls?

Another thing you can try is enabling GraphQL Debug mode under "GraphQL > Settings", then also "Enable GraphQL Query Logs". 

![CleanShot 2024-01-05 at 16 26 44](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/af15af60-8519-430f-b2a0-4ebbe0c3859c)


Then ALSO activate the plugin Query Monitor. 

Then you can see the underyling MySQL queries executed to fulfill the GraphQL request and that might help identify what's going on under the hood. 

For example, I see the following MySQL query under the hood to fulfill this: 

```json
{
  "sql": "\n\t\t\tSELECT  t.term_id\n\t\t\tFROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id\n\t\t\tWHERE t.term_id IN ( 84 )\n\t\t\tORDER BY FIELD( t.term_id, 84 ) ASC\n\t\t\t\n\t\t",
  "time": 0.0001690387725830078,
  "stack": "require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, WPGraphQL\\Router::resolve_http_request, WPGraphQL\\Router::process_http_request, WPGraphQL\\Request->execute_http, GraphQL\\Server\\StandardServer->executeRequest, GraphQL\\Server\\Helper->executeOperation, GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter->wait, GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue, GraphQL\\Executor\\Promise\\Adapter\\SyncPromise->GraphQL\\Executor\\Promise\\Adapter\\{closure}, WPGraphQL\\Data\\Connection\\AbstractConnectionResolver->WPGraphQL\\Data\\Connection\\{closure}, WPGraphQL\\Data\\Loader\\AbstractDataLoader->load_many, WPGraphQL\\Data\\Loader\\AbstractDataLoader->load_buffered, WPGraphQL\\Data\\Loader\\TermObjectLoader->loadKeys, WP_Term_Query->__construct, WP_Term_Query->query, WP_Term_Query->get_terms"
}
```

That is the SQL I would expect to see, given that the ACF Block had the value "84" stored for the "Category" selection on the block:

![CleanShot 2024-01-05 at 16 31 30](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/9e4f978a-4239-463f-a42f-11802791c243)

Perhaps you might be able to identify the raw query that's executing and see if maybe something unexpected is happening? Like maybe a plugin is modifying the WP_Term_Query call or something along those lines?

If you're not already in the WPGraphQL Slack, [perhaps you can join](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA) and maybe we can also coordinate a time to pair and see if we can come up with the culprit?
