### ISSUE TITLE
How to add ACF extensions field types ? No documentations yet

### ISSUE THREAD

**Issue by mathieuCatapulpe** [wp-graphql/wpgraphql-acf#134]
### What problem does this address?

I would like to implement field type for this ACF extension https://github.com/ooksanen/acf-focuspoint but have no idea how

### What is your proposed solution?

Add a doc for ACF extenstion field type

### What alternatives have you considered?

Checked the source code at https://github.com/wp-graphql/wpgraphql-acf/tree/main/src/ThirdParty/AcfExtended but it is still unclear what I have to do in my use case.

**Comment by jasonbahl** [comment]
@mathieuCatapulpe thank you for opening this issue. We have a documentation entry planned for this feature and hope to have the docs live very soon.

**Comment by jasonbahl** [comment]
@mathieuCatapulpe I published a guide on this topic here: https://acf.wpgraphql.com/adding-support-for-3rd-party-acf-field-type/

Please feel free to provide any feedback you might have on this issue or via message in the WPGraphQL Slack ([join here](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA))

I'm going to close this issue as the guide has been published, but we'll keep an eye out in case any feedback is provided.
