### ISSUE TITLE
DUPLICATE_TYPE error when creating options page with same name as field group

### ISSUE THREAD

**Issue by DevMude** [wp-graphql/wpgraphql-acf#139]
### Description

I'm mainly just posting this so other people can find it.

To fix, specify a different `graphql_field_name` for the options page.

```php
acf_add_options_page(array(
  'page_title' => __('Global Components'),
  'menu_title' => __('Global Components'),
  'show_in_graphql' => true,
  'graphql_field_name' => 'globalComponentsPage',
));
```

### Steps to reproduce

1. Add options page:
```php
acf_add_options_page(array(
  'page_title' => __('Global Components'),
  'menu_title' => __('Global Components'),
  'show_in_graphql' => true
));
```
2. Create field group with exact same name (e.g. 'Global Components')
3. Enable graphql query debug logs
4. Run any graphql query

```graphql
query Test {
  __typename
}
```

### PHP or JSON export of the ACF Field Group(s)

[group_6577f98d69296.json](https://github.com/wp-graphql/wpgraphql-acf/files/13644473/group_6577f98d69296.json)

### WPGraphQL Version

1.19.0

### WPGraphQL For ACF Version

Version 2.0.0-beta.6.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.4 Pro

### WordPress Version

6.4.2

### PHP Version

8.1.23

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by josephfusco** [comment]
Hey @DevMude, thanks for posting for visibility.

What you are describing is expected behavior.

Ideally, fields such as "graphql_field_name" would be validated during creation of an ACF Field Group, ensuring that duplicate Types are not being added to the schema, etc. See https://github.com/wp-graphql/wpgraphql-acf/issues/87
