### ISSUE TITLE
Image Field with Return Type URL Returns NULL in Graph

### ISSUE THREAD

**Issue by james0r** [wp-graphql/wpgraphql-acf#145]
Setting return format of image field to **Image ID** works as expected. Switching to return format **Image URL** just returns no nodes just **NULL** in the graphql IDE.

WPGraphQL Version 1.19.0 
WPGraphQL ACF Version 2.0.0

**Comment by jasonbahl** [comment]
@james0r I'm unable to reproduce this on WPGraphQL for ACF v2.0.0

Attached is a field group export of a field group that has 3 image fields, each set to different return types (id, array, url). 

[acf-export-2023-12-27.json](https://github.com/wp-graphql/wpgraphql-acf/files/13782041/acf-export-2023-12-27.json)

Using this field group, I created a new Post and uploaded a different each of the 3 image fields: 

![CleanShot 2023-12-27 at 16 19 16](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/105b49f7-be19-4286-9664-70f7a1900aff)

And I can successfully query each field: 

```graphql
query {
  post(id:7062 idType:DATABASE_ID) {
    id
    title
    ...ImageTest
  }
}

fragment ImageTest on WithAcfImageTest {
  imageTest {
    imageId {
      ...Image
    }
    imageUrl {
      ...Image
    }
    imageArray {
      ...Image
    }
  }
}

fragment Image on AcfMediaItemConnectionEdge {
  node {
    __typename
    id
    mediaItemUrl
    title
  }
}
```

and I get the image as expected for all 3 fields: 

![CleanShot 2023-12-27 at 16 20 09](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/4ee8ba5a-0495-40b2-892e-7470d52222a9)

Can you confirm that you're on WPGraphQL for ACF v2.0.0 and not an older version, such as v0.6.1? 

Can you also confirm that you're on latest WPGraphQL?

If after confirming those 2 things you're still having the issue, can you maybe provide clear steps to reproduce? Right now I'm not sure how to reproduce as things appear to be working as expected. 

Maybe provide a field group export and some example queries you've tried?

**Comment by jasonbahl** [comment]
@james0r i saw you closed this. 

Are you no longer able to reproduce? If you run into it again, let us know so we can investigate further.

**Comment by james0r** [comment]
@jasonbahl Just havn't had time to jump back in that project. Maybe was a version issue. I'll be sure to reopen if I encounter again. Thanks!
