### ISSUE TITLE
Query posts based on ACF values by Registering a Custom “where” Argument

### ISSUE THREAD

**Issue by aleksander-pankow** [wp-graphql/wpgraphql-acf#147]
### Description

Hello.
I detailed read this tutorial : [Query posts based on Advanced Custom Field values by Registering a Custom “where” Argument](https://www.wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument#content)

I added code to my function.php:
```
add_action('graphql_register_types', function () {

    register_graphql_field('RootQueryTo' . 'Event' . 'ConnectionWhereArgs', 'featuredHome', [
        'type' => 'Bool',
        'description' => __('The databaseId of the post object to filter by', 'your-textdomain'),
    ]);
	register_graphql_field('RootQueryTo' . 'Lesson' . 'ConnectionWhereArgs', 'featuredHome', [
        'type' => 'Bool',
        'description' => __('The databaseId of the post object to filter by', 'your-textdomain'),
    ]);
	register_graphql_field('RootQueryTo' . 'ChapterToLessonConnectionWhereArgs', 'featuredHome', [
        'type' => 'Bool',
        'description' => __('The databaseId of the post object to filter by', 'your-textdomain'),
    ]);
});

add_filter('graphql_post_object_connection_query_args', function ($query_args, $source, $args, $context, $info) {

    if (isset($args['where']['featuredHome'])) {
        $query_args['meta_query'] = [
            [
                'key' => 'featured_home',
                'value' => (int) $args['where']['featuredHome'],
                'compare' => '='
            ]
        ];
    }

    return $query_args;
}, 10, 5);
```

lesson/events types filtered by **featuresHome** parameter (field) - I get response.

But from taxonomy **chapter** - parameter not initialised:
<img width="653" alt="Снимок экрана 2023-12-21 в 19 55 16" src="https://github.com/wp-graphql/wpgraphql-acf/assets/111226165/9cae64da-6e08-4108-9033-d0474a723a82">

I also try to add this option from error message (**ChapterToLessonConnectionWhereArgs**):
```
register_graphql_field('RootQueryTo' . 'ChapterToLessonConnectionWhereArgs', 'featuredHome', [
        'type' => 'Bool',
        'description' => __('The databaseId of the post object to filter by', 'your-textdomain'),
    ]);
```

But only error:
```
"errors": [
    {
      "message": "Field \"featuredHome\" is not defined by type ChapterToLessonConnectionWhereArgs.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 16,
          "column": 25
        }
      ]
    }
  ]
```

I want fetch posts from **specific taxonomy** and filtered by **featuredHome** option.

### Steps to reproduce

```
query MyQuery2 {
  lessons(where: {featuredHome: false, language: ALL}) {
    edges {
      node {
        contentTypeName
        title(format: RENDERED)
      }
    }
  }
  chapters(where: {slug: "workshop"}) {
    edges {
      node {
        name
        slug
        description
        lessons(where: {featuredHome: true, language: ALL}) {
          edges {
            node {
              title(format: RENDERED)
            }
          }
        }
      }
    }
  }
}
```

### PHP or JSON export of the ACF Field Group(s)

[acf-export-2023-12-21-2.json](https://github.com/wp-graphql/wpgraphql-acf/files/13745432/acf-export-2023-12-21-2.json)

### WPGraphQL Version

1.19.0

### WPGraphQL For ACF Version

2.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

PRO

### WordPress Version

6.4.1

### PHP Version

7.4.33

### Additional enviornment details

WP GraphQL Polylang

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
> I also try to add this option from error message (ChapterToLessonConnectionWhereArgs):

```php
register_graphql_field('RootQueryTo' . 'ChapterToLessonConnectionWhereArgs', 'featuredHome', [
        'type' => 'Bool',
        'description' => __('The databaseId of the post object to filter by', 'your-textdomain'),
    ]);
    ```
    
 @aleksander-pankow I think you were close here!
 
 Just remove the `'RootQueryTo' . ` at the beginning and I think it should work!

**Comment by jasonbahl** [comment]
@aleksander-pankow another thing you could do, to add the arguments to all connections to the `Lesson` type would be something like: 

```php
// Filter the Connection config
add_filter( 'graphql_wp_connection_type_config', function( array $config, \WPGraphQL\Type\WPConnectionType $connection ) {

        // bail early if the connection is NOT to the  "location" type
	if ( ! isset( $config['toType'] ) || 'location' !== strtolower( $config['toType'] ) ) {
		return $config;
	}

        // Add custom connectionArgs to the connection
	$config['connectionArgs']['featuredHome'] = [
		'type' => 'Bool',
		'description' => __( 'Filter homes with "featured home" field selected.', 'wp-graphql' ),
	];

	return $config;

}, 10, 2 );
```

**Comment by jasonbahl** [comment]
@aleksander-pankow I'm going to close this as I believe my answers should help you resolve things. 

Looking forward to seeing what you create with this stack! 🙌🏻
