### ISSUE TITLE
Clone Fields Do not work Properly

### ISSUE THREAD

**Issue by mude-albij** [wp-graphql/wpgraphql-acf#151]
### Description

I have same field Banner that are clone inside a `flexible layout` and `article` post type
When using graphql on these page with `flexible layout` and `article`

fields inside banner are dispaying null

### Steps to reproduce

import fields
1. create a new page and use banner inside the `flexible layout` fill the images and text fields
2. create a new post and fill the banner content there as well
3. query for page as
```
query page($url:ID!){
  page(id:$url,idType:URI){
    pageComponents{
      pageComponents{
        ... on PageComponentsPageComponentsBannerLayout{
          banner{
            title
            subTitle
            background{
              image{
                desktop{
                  node{
                    mediaItemUrl
                  }
                }
                mobile{
                  node{
                    mediaItemUrl
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

query for article as

```
query articles {
  posts {
    nodes {
      articles {
        banner {
          banner {
            banner {
              title
              subTitle
              background {
                image {
                  desktop {
                    node {
                      mediaItemUrl
                    }
                  }
                  mobile {
                    node {
                      mediaItemUrl
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### PHP or JSON export of the ACF Field Group(s)

[acf-export-2024-01-11.json.zip](https://github.com/wp-graphql/wpgraphql-acf/files/13897582/acf-export-2024-01-11.json.zip)

### Additional context

example for page
![image](https://github.com/wp-graphql/wpgraphql-acf/assets/130020301/bfc5c03e-2ff3-40c3-b876-7e0a7221e657)
example for article
![image](https://github.com/wp-graphql/wpgraphql-acf/assets/130020301/623bf0c9-54e2-4cc7-a75e-570133dae5bd)

### WPGraphQL Version

 1.19.0

### WPGraphQL For ACF Version

2.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

Pro

### WordPress Version

6.4.2

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by mude-albij** [comment]
@josephfusco were you not able to replicate the issue?

**Comment by josephfusco** [comment]
Hey @mude-albij, thanks for creating the issue!
I was able to reproduce this.
There is no solution available at the moment but we will be digging into this.

**Comment by mude-albij** [comment]
@josephfusco Thanks

**Comment by mude-albij** [comment]
@josephfusco Are there any update on this issue?

**Comment by jasonbahl** [comment]
@mude-albij Hello, we do not have a solution for this quite yet. 

Some things to possibly try for troubleshooting: 

- see if "prefix_names" setting on clone fields fixes the bug?
- check what data is coming through to the Resolver of the Image field type and see how it's resolving

**Comment by jasonbahl** [comment]
(didn't mean to close, just meant to leave the above comment)

**Comment by mandytensen** [comment]
Hello! My team is experiencing a similar (possibly the same?) issue with the Clone field. Specifically, when using the Clone field within a Group field, all values from the Clone field (regardless of field type within that Clone) will return `null`. 

I noticed from the ACF field group export included here by @mude-albij, their Clone field also appears to be nested within a Group field.

Using the "prefix_names" setting on clone fields did not fix the issue for me.

I can open a new issue for what my team is experiencing if you like, but I have a suspicion it’s related to this same issue here. Let me know if you’d like more information. I appreciate the work you do and I’m happy to help!

**Comment by jasonbahl** [comment]
@mandytensen if you could open a new issue with as many steps to reproduce as possible including a list of active plugins and versions, an export of the ACF Fields as JSON uploaded as a .zip, and any other information required to reproduce, that would be great! 

You can mention this issue as likely related. 

But ya, the more information we have to reproduce and any context you can provide around debugging steps you've already taken, etc would be very helpful. 

Thanks! 🙏🏻

**Comment by jasonbahl** [comment]
@mude-albij  can you confirm if the changes in #185 work for you? I'll need to write some tests, but wanted to get it in your hands as soon as possible to see if it solves the problems you've run into. 

Thanks 🙏🏻

**Comment by mude-albij** [comment]
@jasonbahl #185 is working fine thanks.

**Comment by jasonbahl** [comment]
@mude-albij thanks for confirming! 🙏
