### ISSUE TITLE
Cloning a field group within a flexible content field without selecting "prefix field names" 

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-acf#172]
### Description

When an ACF Field Group is cloned in a flexible content layout, the Schema fails to load if "prefix field names" is not selected.

### Steps to reproduce

 In a "vanilla" WordPress install with ACF Pro, WPGraphQL and WPGraphQL for ACF:

1. Import the field groups provided in a .zip below
2. Open GraphiQL
3. See that the Schema Loads
4. Search "AcfFieldGroup" in the Schema docs and see "PrimaryFieldGroup" and "SecondaryFieldGroup" as groups that implement the interface

![CleanShot 2024-02-14 at 13 16 17](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/56cd813a-6635-4121-b87c-280324f97089)

5. In the "Cloned Group" field within the "Primary Field Group" flexible content layout, disable the "Prefix Field Names" setting and save. 
6. Open GraphiQL again
7. See that the Schema no longer loads

![CleanShot 2024-02-14 at 13 14 25](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/c7c39fa9-ae97-4563-8bbb-fac5e8adb4d4)

### PHP or JSON export of the ACF Field Group(s)

[acf-export-2024-02-14.json.zip](https://github.com/wp-graphql/wpgraphql-acf/files/14285677/acf-export-2024-02-14.json.zip)

### WPGraphQL Version

1.21.0

### WPGraphQL For ACF Version

2.1.1

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.2 PRO

### WordPress Version

6.4.3

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
Below is a more detailed real-life scenario that I believe is being impacted by this bug. 

This was originally reported in Slack, but I want to detail it here for visibility. 

Environment details for the below scenario:

- WordPress 6.5
- ACF Pro v6.2.7
- WPGraphQL v1.22.1
- WPGraphQL for ACF v2.2.0
- WPGraphQL IDE v1.1.0 

The following is an export of 58 ACF Field Groups: [acf-export-blocks.json](https://github.com/wp-graphql/wpgraphql-acf/files/14876720/acf-export-blocks.json)


If we import this to ACF, then open the WPGraphQL IDE and search for `AcfFieldGroup` we will see the Schema loaded properly and we will see all the `Block*` Types representing these ACF Field Groups in the Schema. 

The following is an export of one ACF Field Group that includes a Flexible Content field, and the layouts within the Flexible Content Fields use "clone" fields to clone the Block field groups: [acf-export-content-blocks.json](https://github.com/wp-graphql/wpgraphql-acf/files/14876715/acf-export-content-blocks.json)

If we import this, along with our other ACF Field Groups, then try and open the WPGraphQL IDE, we will see that the Schema fails to load and returns the following errors: 

- 
```graphql
Interface field BlockPriceComparison_Fields.pricesTable expects type BlockPriceComparisonPricesTable but ContentBlocksBlocksPriceComparisonLayout.pricesTable is type ContentBlocksBlocksPricesTable.
```

```graphql
Interface field BlockProsAndCons_Fields.adverseEffects expects type BlockProsAndConsAdverseEffects but ContentBlocksBlocksProsAndConsLayout.adverseEffects is type ContentBlocksBlocksAdverseEffects.
```

```graphql
Interface field BlockProsAndCons_Fields.positiveEffects expects type BlockProsAndConsPositiveEffects but ContentBlocksBlocksProsAndConsLayout.positiveEffects is type ContentBlocksBlocksPositiveEffects.
```

**Comment by jasonbahl** [comment]
Here's another scenario to test:

1. Import the following ACF Field Groups: [acf-export-2024-04-22.json](https://github.com/wp-graphql/wpgraphql-acf/files/15065574/acf-export-2024-04-22.json)
2. Try to load the Schema in the GraphiQL IDE
3. See the schema fail to load: 

![CleanShot 2024-04-22 at 10 04 42](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/8991bf73-8a74-435e-a091-ec51ca87fb2e)

**Comment by nhankla-kl** [comment]
@jasonbahl  this is amazing! Will test it on 10 or so sites on my end this week. They are similar structure with ACF tweaks. Will let you know. Thank You!
