### ISSUE TITLE
Weird schema with taxonomy ACF field

### ISSUE THREAD

**Issue by gl03** [wp-graphql/wpgraphql-acf#183]
### Description

I have added an ACF image field `featureIcon` to my custom taxonomy `features` and instead of the expected `taxonomy->nodes->acf->field` schema, I get this:

```
features {
    nodes {
      featureIcon {
        fe {
          node {
            sourceUrl
          }
        }
      }
    }
  }
```

This works, and I'm certainly not proposing a breaking change to the default schema, but it's still odd. (what is `fe`?)

### Steps to reproduce

1. add image field to custom taxonomy
2. enable fieldgroup for WPGraphQL

### WPGraphQL Version

1.21.0

### WPGraphQL For ACF Version

2.1.2

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.6.1 Pro

### WordPress Version

6.4.3

### PHP Version

7.4.33

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@gl03 without an export of your ACF Field Group as asked for in the issue template, it will be difficult to provide any helpful information. 

Without more information, my only guess is that the "graphql_field_name" was accidentally set to "fe" on the field?

**Comment by gl03** [comment]
Ah, my bad: the field's `graphql_field_name` was set to `fe`. Must have been an initial typo that wasn't overwritten by later correcting the ACF field name (which it probably shouldn't have been). Sorry for my confusion, stemming in part from the missing `acf` node as compared to posts, but all good. Thank you for your reply and this great plugin!
