### ISSUE TITLE
Range field returns null when value is 0

### ISSUE THREAD

**Issue by andremendonca03** [wp-graphql/wpgraphql-acf#186]
### Description

ACF Range field returns `null` when the value selected is 0.

![Group 297 (3)](https://github.com/wp-graphql/wpgraphql-acf/assets/82763595/10622cd9-32f5-47c7-b32a-4d80afefb5ba)

### Steps to reproduce

1. Create a Range field;
2. Define range field value to 0;
3. Query for range field value.

### WPGraphQL Version

1.21.0

### WPGraphQL For ACF Version

2.1.2

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.6

### WordPress Version

6.4.3

### PHP Version

7.4.33

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@andremendonca03 thanks for reporting this! Hope to reproduce this and look into a solution shortly 🙏🏻

**Comment by jasonbahl** [comment]
@andremendonca03 could you provide an export of your ACF Field Group?

I've tested this and it appears to work as expected:

Here's a Post with a range field set with the value "0"

![CleanShot 2024-03-05 at 19 49 52](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/e8eec80c-ece6-425d-af05-5f973f498e31)

And when queried, I get back a "0"

![CleanShot 2024-03-05 at 19 51 08](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/0b9ac564-76b1-4e48-9b27-8ff097a30919)

**Comment by jasonbahl** [comment]
@andremendonca03 I even tried with a repeater with a range field inside:


![Image](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/be00626f-ecb6-4bbe-a07d-a73996e259fe)

And it still returns a 0 as expected:

![Image](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/f71c7944-0a87-4e01-a6a6-2277959ef948)


Perhaps I'm missing some additional steps to reproduce?

**Comment by richardaubin** [comment]
Both of your query results look different.  Maybe also provide a complete copy of your wpgraphql query, not the results.

**Comment by andremendonca03** [comment]
Ohh apologies for the false alarm! 😞 

I actually was working on a site that is using the old ACF for WPGraphQL (v0.6.1).
Just tried on another site witht the new plugin and it's working correctly!
Sorry for it.

![Screenshot 2024-03-07 at 1 42 53 pm](https://github.com/wp-graphql/wpgraphql-acf/assets/82763595/5da42ebf-6b0f-4afc-9cbf-96e674750e1b)
