### ISSUE TITLE
Add schema linter and breaking change for Pull Requests

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wpgraphql-acf#20]
### What problem does this address?

When submit PR, check the graphql schema for breaking changes against the previous tagged release.

### What is your proposed solution?

As a maintainer, I would like a Github Workflow to run when PRs are opened that compares the GraphQL Schema with the previous release’s Schema

Github Workflow that generates the GraphQL Schema, given a WordPress environment running latest WPGraphQL + ACF + WPGraphQL for ACF and a standard import of ACF Field Groups

Compares the generated schema with most recent release’s schema (artifact uploaded to Github releases)

**Comment by jasonbahl** [comment]
closed by #21
