### ISSUE TITLE
PHP Fatal error: On Plugin Activation

### ISSUE THREAD

**Issue by billiemead** [wp-graphql/wpgraphql-acf#203]
### Description

Upon plugin activatvation a critical error is thrown and WP admin is locked down with white screen:

![image](https://github.com/wp-graphql/wpgraphql-acf/assets/8992422/cabfa0e9-2eba-4fdf-8067-c9465bc83a1e)

### Steps to reproduce

1. Clone plugin to /wp-content/plugins/
2. From WP Admin, attempt to activate WPGraphQL for ACF plugin

### Additional context

from debug.log

```
[08-May-2024 12:06:42 UTC] PHP Fatal error:  Uncaught Error: Class "WPGraphQL\Acf\ThirdParty" not found in G:\laragon-6.0.0\www\ncmaz\wordpress\wp-content\plugins\_wpgraphql-acf\src\WPGraphQLAcf.php:64
Stack trace:
#0 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-includes\class-wp-hook.php(324): WPGraphQLAcf->init_third_party_support('')
#1 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-content\plugins\_wpgraphql-acf\src\WPGraphQLAcf.php(57): do_action('wpgraphql/acf/i...')
#4 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-includes\class-wp-hook.php(324): WPGraphQLAcf->init('')
#5 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#7 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-settings.php(550): do_action('plugins_loaded')
#8 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-config.php(32): require_once('G:\\laragon-6.0....')
#9 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-load.php(50): require_once('G:\\laragon-6.0....')
#10 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-admin\admin.php(34): require_once('G:\\laragon-6.0....')
#11 G:\laragon-6.0.0\www\ncmaz\wordpress\wp-admin\plugins.php(10): require_once('G:\\laragon-6.0....')
#12 {main}
  thrown in G:\laragon-6.0.0\www\ncmaz\wordpress\wp-content\plugins\_wpgraphql-acf\src\WPGraphQLAcf.php on line 64
```

### WPGraphQL Version

1.25.0

### WPGraphQL For ACF Version

2.3.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

Pro v 6.2.9

### WordPress Version

6.5.3

### PHP Version

8.2.0 Win 32 x64

### Additional enviornment details

- Windows 11 OS
- Next.js

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by josephfusco** [comment]
Hey @billiemead, when cloning this repo directly, you'll need to run `composer install` to autoload the classes.

This step has already been handled in the official [releases on GitHub](https://github.com/wp-graphql/wpgraphql-acf/releases) and https://wordpress.org/plugins/wpgraphql-acf/
