### ISSUE TITLE
User ACF field only returns a value if it matches the post author.

### ISSUE THREAD

**Issue by missionmike** [wp-graphql/wpgraphql-acf#234]
### Description

When I set a value for a Users ACF field, sometimes the user value is not returned via GraphQL.

Example below showing:
- Post Author: "User One"
- ACF User in "Users" field: "User Two"
- WPGraphQL response returns empty array.

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/f33aaa02-0e2f-4d17-ad86-0af7f1bb419b">

However, the REST response _does_ include the user value:

<img width="766" alt="image" src="https://github.com/user-attachments/assets/670593ff-a9d6-4326-8df2-d00a65f67648">

When I change the post author to "User Two", I can see the expected result in WPGraphQL response (see Post Author value in right side of screenshot):

<img width="1208" alt="image" src="https://github.com/user-attachments/assets/ad72e874-75ab-4dac-86d5-1c73fc846597">

This issue also affects the ACF Users field when "Select Multiple" is enabled on the field. WPGraphQL will only return one user if it's the post author. Otherwise, the result is empty.

Returns user when user is the same as post author:

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/d522336d-ae40-49f5-9904-ba11f5a7dc11">

Returns empty list when none of users are the post author:

<img width="1211" alt="image" src="https://github.com/user-attachments/assets/e2060072-4099-47fb-abc3-cb38a4933d9c">

However, REST response will consistently return all ACF Users values:

<img width="705" alt="image" src="https://github.com/user-attachments/assets/a53c07ed-853a-401a-a090-e7070b8fc577">

### Steps to reproduce

Use this repository to access a quick minimal reproduction: https://github.com/missionmike/wordpress-minimal-repro-wpgraphql-acf-multiple-users

> Note: this repo is based on a boilerplate I set up [here](https://github.com/missionmike/wordpress-minimal-repro-boilerplate), which is a work in progress. Please let me know if you run into any issues! The goal is to make minimal repro setup fast and easy within VS Code.

Steps to reproduce are included in the README, but I will paste the general steps here:

1. Set up an ACF field for "Users" and add to posts.
2. Assign a user to this field in a test post. Ensure that this user is NOT the same user as the post author.
3. Fetch the WPGraphQL response for this post. The ACF Users value is empty.
4. Change the post author to match the ACF user (or vice-versa).
5. Refetch with WPGraphQL and you should see the correct user in the ACF User field.

### PHP or JSON export of the ACF Field Group(s)

[group_66be57e0d401c.json.zip](https://github.com/user-attachments/files/16630013/group_66be57e0d401c.json.zip)

### WPGraphQL Version

1.28.0

### WPGraphQL For ACF Version

2.4.1

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.3.5 Free

### WordPress Version

6.6.1

### PHP Version

8.2.22

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by missionmike** [comment]
I plan to dive into this to learn a bit more about how this works under the hood. If I make progress perhaps I can open a PR to patch.

If anyone could point me to a place in the code that handles this functionality, it could give me a head start.

Thanks to everybody involved for working on these plugins!

**Comment by josephfusco** [comment]
Hey @missionmike, I believe that this is related to users not being public by default, until they author a published post. You can read more about that here https://www.wpgraphql.com/docs/users#sensitive-data.

We also have a post about how to make users public https://www.wpgraphql.com/2020/12/11/allowing-wpgraphql-to-show-unpublished-authors-in-user-queries

Hoping this helps! If you believe that this could be a different issue, feel free to add more details below.

**Comment by missionmike** [comment]
@josephfusco wow! I searched all over and didn't stumble across this article. This worked perfectly. Thank you so much.

I tested by adding these hooks to `functions.php` in my minimal repro, as stated in the [article you shared](https://www.wpgraphql.com/2020/12/11/allowing-wpgraphql-to-show-unpublished-authors-in-user-queries):

```
add_filter( 'graphql_connection_query_args', function( $query_args, $connection_resolver ) {

    if ( $connection_resolver instanceof \WPGraphQL\Data\Connection\UserConnectionResolver ) {
      unset( $query_args['has_published_posts'] );
    }
  
    return $query_args;
  
}, 10, 2 );

add_filter( 'graphql_object_visibility', function( $visibility, $model_name, $data, $owner, $current_user ) {

    // only apply our adjustments to the UserObject Model
    if ( 'UserObject' === $model_name ) {
      $visibility = 'public';
    }
  
    return $visibility;
  
}, 10, 5 );
```

Results in Postman using "select multiple" on the post that has "admin" as the author, and using two author users in ACF without published posts:

![image](https://github.com/user-attachments/assets/6f39b5c8-13aa-4887-96ca-935046d72eb7)

Sorry I didn't find this earlier, but perhaps this issue's SEO will help others who stumble across the same issue in the future.

Thanks so much for getting back to me! Seems like this can be closed so I'll close it out.
