### ISSUE TITLE
Clone Fields not resolving properly

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-acf#49]
### Description

Cloning a field group then querying for the cloned fields leads to `null` results

### Steps to reproduce

- Import the 2 field groups provided below (adjust the location rules as necessary to have the field group show up in the admin)
- Edit the page the field group was assigned to, filling in values for the "cloned_text_field" and "cloned_image_field"
- Save the page (and ensure that the values persisted)
- Query the page in GraphQL, querying the cloned fields 

```graphql
{
  nodeByUri(uri: "kitchen-sink") {
    __typename
    isContentNode
    ...WithAcfPro
  }
}

fragment WithAcfPro on WithAcfAcfProKitchenSink {
  acfProKitchenSink {
    clonedTextField
    clonedImageField {
      node {
        sourceUrl
      }
    }
  }
}
```

- See that the results are null for the cloned fields: 
![CleanShot 2023-06-02 at 12 17 18](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/0415b2f4-0130-4602-becd-11f87c3e3ba9)

- However, if we query for the cloned fields on a flex field, we do see the values as expected! 

```graphql
{
  nodeByUri(uri: "kitchen-sink") {
    __typename
    isContentNode
    ...WithAcfPro
  }
}

fragment WithAcfPro on WithAcfAcfProKitchenSink {
  acfProKitchenSink {
    flexibleContent {
      __typename
      ...CloneLayout
    }
    clonedTextField
    clonedImageField {
      node {
        sourceUrl
      }
    }
  }
}

fragment CloneLayout on AcfProKitchenSinkFlexibleContentLayoutWithClonedGroup {
  clonedTextField
  clonedImageField {
    node {
      sourceUrl
    }
  }
}
```

![CleanShot 2023-06-02 at 12 21 50](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/0ec7dd66-d502-40c9-ae33-49d81a019109)

So, the bug seems to be related to clone fields at the root of a group? 🤔 

### PHP or JSON export of the ACF Field Group(s)

[acf-export-2023-06-02.json.zip](https://github.com/wp-graphql/wpgraphql-acf/files/11637952/acf-export-2023-06-02.json.zip)

### WPGraphQL Version

1.14.3

### WPGraphQL For ACF Version

2.0.0-beta.2.4.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

PRO

### WordPress Version

6.2

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
This has been addressed by WPGraphQL v1.14.4 passing along connection config to the field registered to represent the connection, allowing for clone fields to access the original ACF Field from within resolvers. 

see: https://github.com/wp-graphql/wp-graphql/pull/2826

### Before

![CleanShot 2023-06-14 at 09 15 01](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/909807d2-1504-4f16-bfc6-eec455370524)

### After

![CleanShot 2023-06-14 at 09 17 18](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/377944f1-7de8-4657-bd67-bfa2c9beb8ff)

**Comment by claus** [comment]
@jasonbahl Did this regress in latest WPGraphQL versions by any chance? I get pretty much exactly the erratic behavior described in this ticket in WPGraphQL 2.0.0 with WPGraphQL for ACF 2.4.1

I think i'm going to open a new ticket for my case, still poking around, the behavior seems to vary depending on the "Fields" (selecting individual fields to clone works, selecting "all fields from field group" does not) and "Display" settings ("Seamless" works better than "Group" for whatever reason).

**Comment by YCMitch** [comment]
Yeah, similar problem here. 'Seamless' seems to work okay. For 'Group' they don't even appear as available fields when introspecting.
