### ISSUE TITLE
fieldGroupName always rendering "null"

### ISSUE THREAD

**Issue by TheHatcheryLabs** [wp-graphql/wpgraphql-acf#64]
### Description

Within GraphQL IDE, the fieldGroupName field within a pageBy query will always render as "null" when trying to reference flexible content fields within ACF. There's no way to determine in .vue which flexible content layout you want to display.

![Screenshot 2023-07-19 at 12 26 55 PM (2)](https://github.com/wp-graphql/wpgraphql-acf/assets/39837021/1fa8d5da-4bb9-450c-9067-b3622ded0e9b)

### Steps to reproduce

1. Enable ACF Pro 6.1.7, WPGraphQL 1.14.7, WPGraphQL for ACF 2.0.0-beta.3.1.0
2. Go to GraphQL IDE
3. Create new query with pageBy (reference screenshot)

![Screenshot 2023-07-19 at 12 26 55 PM (2)](https://github.com/wp-graphql/wpgraphql-acf/assets/39837021/fa5cf395-8068-4042-9f4c-82ef6bf2d267)

### WPGraphQL Version

1.14.7

### WPGraphQL For ACF Version

2.0.0-beta.3.1.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

Free

### WordPress Version

6.2.2

### PHP Version

8.1.9

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@TheHatcheryLabs thanks for reporting. 

I was able to reproduce. Hope to have this resolved soon.
