### ISSUE TITLE
`FILTER_SANITIZE_STRING` deprecated

### ISSUE THREAD

**Issue by mindctrl** [wp-graphql/wpgraphql-acf#69]
### Description

I'm getting a deprecated notice when adding/editing ACF Field Groups in wp-admin.

> PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in wp-content/plugins/wpgraphql-acf/src/Admin/Settings.php on line 154

I'm running PHP 8.1.9 at the moment. Looks like this constant was deprecated in 8.1.x. https://www.php.net/manual/en/filter.filters.sanitize.php

### Steps to reproduce

1. Install and activate this plugin.
2. Create field group
3. See notice

### WPGraphQL Version

1.14.9

### WPGraphQL For ACF Version

Latest main branch

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.1.7 free

### WordPress Version

6.2.2

### PHP Version

8.1.9

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@mindctrl I was able to reproduce this: 

![CleanShot 2023-08-03 at 16 40 06](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/323ba2d2-259a-4fc3-8618-a5767e35aa98)

Working on a fix now. Thanks! 🙏🏻
