### ISSUE TITLE
Create and update mutations should be created with post types or field groups

### ISSUE THREAD

**Issue by ArkDouglas** [wp-graphql/wpgraphql-acf#75]
### What problem does this address?

This allows wpgrpahql-acf to fully empower the use of graphql for ACF.   Currently, it only exposes read support. 

### What is your proposed solution?

Registration hooks similar to atlas content modeler that allow the fields and post types to expose the meta fields necessary for creating and updating via GraphQL

### What alternatives have you considered?

Custom coding, which nullfiies the purpose of the ACF and wpgraphql-acf combo, so it's more of an 'abandon' then a solution. 

### Additional Context

Atlas Content Modeler allows creating custom types and then registers the proper mutations in graphql to support updating and creating the content via graphql.

**Comment by justlevine** [comment]
Never used ACM, but would like to weigh in from a security perspective that if this does get added any ACF fields should have to _opt in_ via a toggle to be available as a mutation input.

There's no GUI for a permissions layer, and most users defining their GraphQL fields with ACF aren't of the demographic that would naturally pause to consider whether they want anyone who can run the mutation to be able to update certain ACF values.

**Comment by jasonbahl** [comment]
Hey! 

We plan to visit this at some point, but there's some limitations to GraphQL that we believe make this hard / impossible to achieve in an optimal way. 

GraphQL has Interfaces and Unions for querying data, but does not have the same concept for Inputs. We believe this is necessary to fully support Mutations for ACF.

I've been wanting this feature in GraphQL for a long time (see: https://github.com/graphql/graphql-js/issues/207#issuecomment-351592210). 

There's been progress made with the `@oneOf` directive, which was recently merged into GraphQL-JS, but not yet formally released, and not yet formally added to the GraphQL Spec. 

Once it makes its way to the GraphQL Spec and a formal release of GraphQL-JS, I anticipate GraphQL-PHP adding this functionality making it possible for WPGraphQL to then take advantage of it as well. 

----

I also agree with @justlevine that there should also be more consideration as to who should / should not be able to mutate specific fields. (fwiw, I think this should happen at a wider level than WPGraphQL. ACF should, in my opinion add a more granular field-level permission system that all APIs (WPGraphQL, REST, CLI, the wp-admin, etc) should be able to benefit from.

**Comment by jasonbahl** [comment]
I'm going to close this in favor of #109 where we'll track this going forward
