### ISSUE TITLE
Error after activation

### ISSUE THREAD

**Issue by ludo-mon-key** [wp-graphql/wpgraphql-acf#79]
### Description

After activating the plugin, the system generates error:
[Wed Aug 30 16:35:52.829998 2023] [php7:error] [pid 17058] [client 151.71.53.120:55082] PHP Fatal error:  Uncaught Error: Class 'WPGraphQL\\Acf\\ThirdParty' not found in /wp-content/plugins/wpgraphql-acf-main/src/WPGraphQLAcf.php:51

### Steps to reproduce

Upload the plugin zip
Click on the button: activate

### WPGraphQL Version

1.15.0

### WPGraphQL For ACF Version

v2.0.0-beta.4.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2

### WordPress Version

6.3

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@ludo-mon-key make sure you get the plugin from the latest release: https://github.com/wp-graphql/wpgraphql-acf/releases

![CleanShot 2023-08-30 at 16 04 47](https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/6bf275d6-c930-4e7a-adb0-352dd14eb48c)

If you download the plugin directly from Github, it won't have dependencies loaded.

**Comment by jasonbahl** [comment]
@ludo-mon-key I'm going to close this as I believe installing from the latest release zip should fix this, but if it's still an issue, let me know 🙏🏻
