### ISSUE TITLE
Warning: Undefined array key "AcfOptionsPage"

### ISSUE THREAD

**Issue by djmtype** [wp-graphql/wpgraphql-acf#82]
### Description

I'm getting this error in the admin under ACF's settings for each field group: 

```
Warning: Undefined array key "AcfOptionsPage" in /Volumes/Evo/Local/sandbox/app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php on line 437
GraphQL Types to Show the Field Group On
```

I'm also unsure if the issue is with this extension or the WPGraphQL plugin.

<img width="1120" alt="Screenshot 2023-09-01 at 12 13 35 PM" src="https://github.com/wp-graphql/wpgraphql-acf/assets/930713/5964bd7d-b769-457a-a70f-e053667329aa">

### Steps to reproduce

1. Created field group
2. Saved field group

### WPGraphQL Version

1.16.0

### WPGraphQL For ACF Version

2.0.0-beta.4.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.0 Pro

### WordPress Version

6.3.1

### PHP Version

8.1.9

### Additional enviornment details

Using Local by WPEngine with Sage 10.5 theme.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by djmtype** [comment]
BTW, this issue seems to go away after creating an Options page; just pointing this out when no Options page is registered.

**Comment by jasonbahl** [comment]
@djmtype thanks for reporting! Looking into this 👀

**Comment by jasonbahl** [comment]
@djmtype this took me a minute to reproduce, but I was able to reproduce this if I set the location rules to the following: 

<img width="1451" alt="CleanShot 2023-09-05 at 10 01 43@2x" src="https://github.com/wp-graphql/wpgraphql-acf/assets/1260765/7225d999-dac0-4100-a21e-9b99ca060304">

Looking into preventing this error when the location rule is set to something invalid (either blank or the name of an options page that no longer exists)
