### ISSUE TITLE
Support "show_in_graphql" for ACF Options Pages new UI rolled out with ACF v6.2.0

### ISSUE THREAD

**Issue by exp-endurance** [wp-graphql/wpgraphql-acf#83]
### What problem does this address?

This would address inconsistency between ACF Options Pages new UI and all the ACF Fields Groups UI, ACF Fields UI, etc

The latters show a handy "Show in GraphQL?" flag to display ACF data in the GraphQL schema at the end of the creation process UI, the former (which was just recently rolled out) doesn't, so the UI cannot be used to create Options Pages compatible with WPGraphQL.

### What is your proposed solution?

I would like a "Show in GraphQL?" flag to display ACF Options Pages data in the GraphQL schema at the end of the Options Page creation process UI.

### What alternatives have you considered?

n/a

**Comment by jasonbahl** [comment]
@exp-endurance yo, check it: https://github.com/wp-graphql/wpgraphql-acf/pull/86

Let me now if you're able to pull it down and test it. 

(fwiw, You should be able to clone this repo, check out this branch, then run `composer build-plugin` to get a built version of the plugin you can test with)

**Comment by exp-endurance** [comment]
Will check it out asap (in 24-48hrs i reckon) on a test setup and let you know, thank you so so much!
