### ISSUE TITLE
Fatal error: Uncaught Error: Class "WPGraphQL\Acf\ThirdParty" not found

### ISSUE THREAD

**Issue by fraubungle** [wp-graphql/wpgraphql-acf#90]
### Description

When trying to activate v2.0.0-beta.5.0.0 which I downloaded and added to WordPress via the add plugin page I get the following error

Fatal error: Uncaught Error: Class "WPGraphQL\Acf\ThirdParty" not found in /Users/markellis/Local Sites/vchackneybackend/app/public/wp-content/plugins/wpgraphql-acf-release-v2.0.0-beta.5.0.0/src/WPGraphQLAcf.php:51 Stack trace: #0 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-includes/class-wp-hook.php(310): WPGraphQLAcf->init_third_party_support('') #1 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array) #2 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-content/plugins/wpgraphql-acf-release-v2.0.0-beta.5.0.0/src/WPGraphQLAcf.php(44): do_action('wpgraphql/acf/i...') #4 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-includes/class-wp-hook.php(310): WPGraphQLAcf->init('') #5 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) #6 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #7 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-settings.php(495): do_action('plugins_loaded') #8 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-config.php(103): require_once('/Users/markelli...') #9 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-load.php(50): require_once('/Users/markelli...') #10 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-admin/admin.php(34): require_once('/Users/markelli...') #11 /Users/markellis/Local Sites/vchackneybackend/app/public/wp-admin/plugins.php(10): require_once('/Users/markelli...') #12 {main} thrown in /Users/markellis/Local Sites/vchackneybackend/app/public/wp-content/plugins/wpgraphql-acf-release-v2.0.0-beta.5.0.0/src/WPGraphQLAcf.php on line 51

I am running Local as my testing environment and the plugins installed are 

Advanced Custom Fields PRO - Version 6.2.1.1 
WPGraphQL - Version 1.16.0
WPGraphQL ACF - Version 2.0.0-beta.5.0.0

I did have the older version running initially 
WPGraphQL for Advanced Custom Fields - Version 0.6.1

I also had Field Groups and Post Types created within ACF, but after the error I removed them all via the UI and deleted permanently.

I am sure I have f'd up somewhere and if anyone can let me know what I did wrong that would be fantastic.

### Steps to reproduce

1. Activate WPGraphQL ACF - Version 2.0.0-beta.5.0.0 with WPGraphQL - Version 1.16.0 active or vice verser
2. If ACF is deactivated you can activate both WPGraphQL ACF - Version 2.0.0-beta.5.0.0 with WPGraphQL - Version 1.16.0 but when you active ACF the same error happens.

### WPGraphQL Version

1.16.0

### WPGraphQL For ACF Version

2.0.0-beta.5.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

Pro

### WordPress Version

6.3.1

### PHP Version

8.2.10

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@fraubungle it appears that you maybe installed the plugin via cloning from the repo directly or downloading the .zip from the repo directly. 

If you cloned this repo, then you will need to run `composer install --no-dev` to install the dependencies, including the Autoloader. 

If downloading a .zip, download from the [releases](https://github.com/wp-graphql/wpgraphql-acf/releases) page. Each release has a .zip that you can download which has all dependencies already included. 

This will be covered in our upcoming documentation.

The plugin will also be available on WordPress.org soon, although no ETA as the plugin review queue is backed up pretty badly. (
