### ISSUE TITLE
GraphQL Single and Plural Name have no effect on ACF post types

### ISSUE THREAD

**Issue by stefanmomm** [wp-graphql/wpgraphql-acf#96]
### Description

I have imported my custom post types from Custom Post Type UI into ACF PRO. But now when I want to set GraphQL Single and Plural Name, they are ignored. Instead, Single and Plural Name of the post type are used. This also seems to be the case when I recreate Custom Post Types directly in ACF without importing from CPT UI.
Also, using umlauts in post type labels seems to break everything.

<img width="653" alt="Bildschirm­foto 2023-10-04 um 17 29 16" src="https://github.com/wp-graphql/wpgraphql-acf/assets/10480858/b46abc60-3f63-430a-adfe-9ad41fd2691f">
<img width="660" alt="Bildschirm­foto 2023-10-04 um 17 29 22" src="https://github.com/wp-graphql/wpgraphql-acf/assets/10480858/52988b90-9e76-47db-ba30-dfdd2fc69a5d">
<img width="398" alt="Bildschirm­foto 2023-10-04 um 17 29 32" src="https://github.com/wp-graphql/wpgraphql-acf/assets/10480858/66cf61a9-14a2-4aa1-a167-1b98c06bca1f">

### Steps to reproduce

1. Create a new post type in ACF (PRO).
2. Activate the "Show in GraphQL" toggle.
3. Change the values for GraphQL Single Name and GraphQL Plural Name.
4. Check in GraphiQL IDE if the changes of single and plural name were successful.

### WPGraphQL Version

1.16.0

### WPGraphQL For ACF Version

2.0.0-beta.5.0.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.2.1.1 (Pro)

### WordPress Version

6.3.1

### PHP Version

8.2.10

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@stefanmomm I believe this _might_ be an issue with how ACF handles imports from CPT UI. 

I'll try and look into it and see if it's a WPGraphQL for ACF bug, but I think it _might_ be a core ACF import bug.

**Comment by jasonbahl** [comment]
@stefanmomm ok, I chatted with @mattgrshaw and he pointed me to a bug in this repo. 

PR coming to address this.

**Comment by stefanmomm** [comment]
Thank you so much @jasonbahl!
