### ISSUE TITLE
ACF Field Groups registered to a Page Template aren't automatically added to the Schema

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-acf#97]
When adding an ACF Field Group to a page template, the field group is not automatically added to the schema, and the user must manually assign the Template's GraphQL Type to be associated with in the Schema

**NOTE**: this was reported in Slack

**Comment by kpoelhekke** [comment]
When assigning the fields manually the fields are included in the schema, but the returned values are `null`.

![image](https://github.com/wp-graphql/wpgraphql-acf/assets/1632377/59d24e96-ade4-4516-9bdc-c7e2c14a2f7e)
![image](https://github.com/wp-graphql/wpgraphql-acf/assets/1632377/088b74a0-eb5c-40f3-8261-a0a234527a43)

**Comment by kpoelhekke** [comment]
I've been able to circumvent this for now using the following filter:

```php
add_filter('wpgraphql/acf/pre_get_node_acf_id', function ($id, $node) {
    if (is_array($node) && isset($node['templateName'])) {
        global $post;
        return $post->ID;
    }

    return $id;
}, 10, 2);
```

**Comment by kpoelhekke** [comment]
I found out that `\WPGraphQL\Utils\Utils::format_field_name` is stripping out the underschore in `Template_Home`. So the location rules will return `TemplateHome` instead. That's why automatic assignment doesn't work. If you manually select the template it will however return `Template_Home`.

**Comment by kpoelhekke** [comment]
@jasonbahl I believe that part of the problem still exists. The schema is now working correctly, but the values returned are still `null`.

**Comment by jasonbahl** [comment]
👀 let me see if I can reproduce

**Comment by jasonbahl** [comment]
I've reproduced and opened #110 to follow up. PR incoming.
